### ISSUE TITLE
Create new and update existing performance profiles in the repo & Push to Join Page

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#124]
The performance profile pages need to be updated with the new content generated by the team.

Writing Lab Copy Request Issue: 18F/writing-lab#65
- [x] Content designer
- [x] Director of Outreach #141 (Pending 18F/writing-lab#55)
- [x] Acquisition Specialist #133 
- [x] Data Architect #134 
- [x] Practical Dev #135
- [x] Product Lead #136
- [x] Software Developer (Front-End, Back-End, Full-Stack) #137
- [x] Front End Designer #138
- [x] User Experience Designer #139
- [x] Visual Designer #140

Once all files are merged:
- [x] Change all appropriate files to "Active: true"
- [x] Merge #183  - Updates the roles and teams page with all previous changes

**Comment by pixelwake** [comment]
Content Designer profile created #125

**Comment by fureigh** [comment]
@rooneywp JFYI if you like checkboxes (I do), here's how to do 'em in Markdown:
- [x] Content designer
- [ ] Whatever's next
- [ ] Etc.

You can edit the issue description up at the top of this page. The downside is that editing the description to check additional boxes doesn't trigger a GitHub notification, but they're handy for work-in-progress pull requests and such.

No pressure to add checkboxes here, of course, just thought I'd share.

**Comment by pixelwake** [comment]
Created writing lab issue and updated the original issue description with the appropriate links.

**Comment by fureigh** [comment]
@rooneywp Thanks! A technical note: it'll need to be `active: true`, not `Active: TRUE`, to work. Mind updating the above?

**Comment by fureigh** [comment]
(edited my last comment to fix a confusing typo ('false' instead of 'true'))

**Comment by JennMoran** [comment]
@rooneywp I have a new profile for consulting to add to our website #166

**Comment by fureigh** [comment]
@rooneywp Closed by #183?

**Comment by pixelwake** [comment]
@fureigh I committed changes to the appropriate files setting active to true. #183 closes this issue.
