### ISSUE TITLE
Join Page: Qualification Process Update 

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#143]
Need: Update the join page to include information about the qualification process, including category rating. This is to meet policy requirements as well as to inform the applicant.
- [x] Basis of Rating: Category Rating Section & qualifications bands #149 
- [x] Veteran's Preference Section #149 
- [x] General timelines for qualification process - To #75
- [x] Application modification language

Closing #14 - Information captured here

**Comment by pixelwake** [comment]
Closing this issue. Language was added to the application response that states a estimated timeline.

**Comment by fureigh** [comment]
Thanks, @rooneywp! Just so we know without having to submit a test application, what's the current language about that estimated timeline?

**Comment by pixelwake** [comment]
@fureigh Here is the current auto response email:

Hi (Name),

Thank you for your interest in 18F! We wanted to let you know we received your application for (position), and we are delighted that you would consider joining our team.

The review process takes about 3-5 weeks to complete at which point we will be in touch if your qualifications match our needs for the role. If you are not selected for this position, keep an eye on our jobs page as we're growing and adding openings.

Best, The 18F Team

**Comment by fureigh** [comment]
:+1: Thanks for the info.

**Comment by fureigh** [comment]
@rooneywp Is it possible to also show it on the application confirmation screen post-submission?

**Comment by pixelwake** [comment]
@fureigh No, Lever doesn't provide that kind of configuration option.

**Comment by fureigh** [comment]
@rooneywp Ah, too bad. Thanks for checking.
