### ISSUE TITLE
Joining 18F App: Transition to Lever

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#189]
## Test and Prep for Cutover to Lever hosted app

**Based on the mock up workflow below each role must have a link to it's own application. To prep for cutover and test the application process, these changes must be completed.**
- [x] Update Join Page landing page apply link to direct to roles and teams #204 
- [x] Update How to Apply page apply link to direct to roles and teams #205 

**Updated active Position Files to include an Apply link**
- [x] Design and Product Strat #207 
- [x] Front End Design #208 
- [x] Visual Design #209
- [x] Product lead  #210
- [x] Software dev #211
- [x] SRE #212

**Test**
- [x] Update Director of Outreach to route to Lever #206 
## Mock Up

We are working through the configuration of Lever and will soon be transitioning to using the Lever hosted application. Configuring the application can all be done in app, but I wanted to share what the application looks like and how I'm proposing we initially integrate the Lever application to our site.

Here is a quick mock up of what I'm thinking:

https://drive.google.com/open?id=1RtZqkZg6nGtn3IIAce7rEHHuQS2De7tYTrThygu7MwQ

We will add a link to the Lever application at the bottom of the profile for each role. We will change the "apply" links to direct to the "Roles and Teams" page instead of directly to the application.

**Comment by fureigh** [comment]
Thanks for the mockup! Makes sense to me.

I do want us to move back to dynamically generating the list of open positions, as was the case before the quick changes on September 22nd ([see this example](https://github.com/18F/joining-18f/blob/6fffe4ddb5a1815ad8b62b886d328e20525582db/pages/who-we-are-hiring.md)). I'll file an issue for that and am mentioning it here because it'll affect how the Lever links are incorporated into the codebase.

**Comment by fureigh** [comment]
Filed #192.

**Comment by pixelwake** [comment]
@fureigh I updated this issue to contain the items to prepare/test for the cutover.

**Comment by fureigh** [comment]
@rooneywp :+1: So PR #23 contains the work and this issue exists to ensure that that work is visible in the issue queue, right?

**Comment by pixelwake** [comment]
@fureigh Right, this issue consolidates all PRs for tracking and to give context to the changes. The work is in PRs #204 to #212, I linked to all in the original comment.

**Comment by fureigh** [comment]
Thanks, @rooneywp. I posted replies (including some questions) in those PRs; take a look and let me know what you think. Happy to talk in realtime if that's more efficient.

**Comment by fureigh** [comment]
Merging on an ongoing basis (rather than with #206 as a test) per conversation with @rooneywp.

**Comment by fureigh** [comment]
@rooneywp Took another swing through and merged all but #204, #205 and #208, which have new questions.

**Comment by pixelwake** [comment]
@fureigh I made the changes/updates to #204 #205 and #208. Ready for review.

**Comment by fureigh** [comment]
@rooneywp I think this is all set! Please review and close to confirm.

**Comment by pixelwake** [comment]
@fureigh :+1: I tested the links and everything appears to be working. :tada:

**Comment by fureigh** [comment]
![colbert-eagle-fist-bump](https://cloud.githubusercontent.com/assets/1244599/12040932/dfeb409c-ae21-11e5-9dea-aaa223d28a3d.gif)
