### ISSUE TITLE
Update Join Page to Support RaaS

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#304]
We are currently engaged in two Recruiting as a Service (RaaS) projects. In order to support the successful delivery of those projects, we need to post the positions on our join page so we can direct people to express their interest.

To do this we will need:
- A way to share the information about the specific roles
- A way to share information about the client fellowships
- A way for people to submit their information/express their interest
- [x] Join Page Update #310

**EPA Positions**
- [x] EPA Tech Arch - TAPD #306
- [x] EPA Tech Arch - OTAQ #305
- [x] EPA Cloud Arch - NCC #303

**HUD Positions**
- [x] HUD UX, Info Arch #307
- [x] HUD UX, Research #308
- [x] HUD Product Lead #309
- [x] HUD Data Dev #312 
- [x] HUD Data Tech Arch #311

**Comment by pixelwake** [comment]
@fureigh Going to need your support with this one. I am thinking that MVP here is to add a section to our Open Positions page for RaaS and list the positions under there. Have a page for each position that houses all the content.

As far as application goes, we could use our existing google app but it will need to be modified. Given the timing (we need this live by monday), I'm leaning more toward the MVP being just having people send an email with their resume attached and using the position name in the subject.

Let me know if you want to chat about this.

**Comment by fureigh** [comment]
@rooneywp Let's have a quick chat. I just added one to your calendar for this afternoon.

That MVP sounds viable, assuming the addition of other fields applicants will be asked to include. (And with the understanding that, with all due respect, applicants may fail to include requested fields.)

**Comment by fureigh** [comment]
It'd be preferable to link to agency-branded position descriptions hosted on the agencies' sites. Given that that doesn't seem to be possible, let's include as much information as possible in the position descriptions themselves so they work as standalone pages.

**Comment by fureigh** [comment]
@rooneywp When these PRs are ready for review, please assign them to me and ping me in Slack. Thanks!

**Comment by pixelwake** [comment]
@fureigh Assigned and ready for review.

**Comment by fureigh** [comment]
@rooneywp I'm in transit today for another project but made an initial round of edits.

Can you have someone from the content team review the new files and make the necessary remaining changes for consistency with our style guide, etc.? I'll queue up #310 in the meantime.

**Comment by fureigh** [comment]
Please also add locations to the positions. Thanks!
